---
- name: Install Odoo
  hosts: odoo
  become: true
  become_method: sudo
  vars_files:
    - crid.yml
  tasks:
    - name: Update System
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Upgrade system
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: required package
      apt:
        name:
          - nginx
          - python3-pip
          - build-essential 
          - wget 
          - python3-dev 
          - python3-venv 
          - python3-wheel 
          - libfreetype6-dev 
          - libxml2-dev 
          - libzip-dev 
          - libldap2-dev 
          - libsasl2-dev 
          - python3-setuptools 
          - node-less 
          - libjpeg-dev 
          - zlib1g-dev 
          - libpq-dev 
          - libxslt1-dev 
          - libldap2-dev 
          - libtiff5-dev 
          - libjpeg8-dev 
          - libopenjp2-7-dev 
          - liblcms2-dev 
          - libwebp-dev 
          - libharfbuzz-dev 
          - libfribidi-dev 
          - libxcb1-dev
                  


    - name: git odoo vars_files
      ansible.builtin.git:
        repo: https://github.com/odoo/odoo.git
        dest: /opt/odoo{{odoo_version}}
        version: "{{odoo_version}}"
        depth: 1

    - name: download wkhtmltopdf
      ansible.builtin.get_url:
        url:  https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        dest: /tmp

    - name: Install wkhtmltopdf 
      ansible.builtin.apt:
        deb: /tmp/wkhtmltox_0.12.5-1.bionic_amd64.deb


    - name: Install Odoo Requirements.txt
      ansible.builtin.pip:
        requirements: /opt/odoo15.0/requirements.txt

    - name: Create Odoo Group
      ansible.builtin.group:
        name: odoo
        state: present
    
    - name: create projects dirs
      ansible.builtin.file:
        path: /opt/odoo{{odoo_version}}/projects 
        state: directory
        group: odoo
        mode: 0770
        recurse: true

    - name: create runs dir
      ansible.builtin.file:
        path:  /opt/odoo{{odoo_version}}/runs
        state: directory
        group: odoo
        mode: 0770
        recurse: true

    - name: create etc odoo dir
      ansible.builtin.file:
        path: /etc/odoo
        state: directory

    - name: Create log dir
      ansible.builtin.file:
        path: /var/log/odoo
        state: directory
        group: odoo
        mode: 0770
        recurse: true


    - name: Create user home 
      ansible.builtin.user:
        name: "{{username}}"
        group: odoo
        home: /opt/odoo{{odoo_version}}/projects/{{username}}
        shell: /sbin/nologin

    - name: data dirs
      ansible.builtin.file:
        path: /opt/odoo15.0/projects/{{username}}/data
        group: odoo
        owner: klash
        mode: 0770
        state: directory

    - name:  custom dirs
      ansible.builtin.file:
        path: /opt/odoo15.0/projects/{{username}}/custom
        group: odoo
        owner: klash
        mode: 0770
        state: directory

      
    - name: Create a python3 link
      ansible.builtin.file:
        src: /bin/python3
        dest: /bin/{{username}}
        state: link


    - name: copy config file
      ansible.builtin.template:
        src: config.j2
        dest: /etc/odoo/{{username}}.conf

    - name: copy service file
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/{{username}}.service

    - name: daemon reload and start/enable service
      ansible.builtin.systemd:
        daemon_reload: yes
        name: "{{username}}.service"
        state: started
        enabled: true


    - name: Configure reverse proxy
      ansible.builtin.template:
        src: nginx.j2
        dest: /etc/nginx/conf.d/{{username}}.conf
      
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

        


    